app:
  id: apollo-test1
apollo:
  meta: http://localhost:8080
  namespaces: application
  eagerLoad:
    enabled:true


spring:
  application:
    name:  cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
eureka:
  instance:
    instance-id: payment8001
    prefer-ip-address: true
    # lease-renewal-interval-in-seconds:   客户端向服务端发送心跳的时间间隔
    #lease-expiration-duration-in-seconds:  服务端收到最后一次心跳后等待时间上限，超时剔除
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone:  http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
      defaultZone:  http://localhost:8080/eureka

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.study.springboot.entities