server:
  port: 84

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka

spring:
  application:
    name: cloud-comsumerOrder-service
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:9999
        port: 8719

management:
  endpoints:
    web:
      exposure:
        include: '*'