server:
  port: 9004


spring:
  application:
    name:  cloud-payment-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'
