server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka

spring:
  application:
    name: cloud-order-service

logging:
  level:
    com.study.springcloud.service: debug

feign:
  hystrix:
    enabled: true